import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header className="bg-gray-800 py-6">
          <div className="container mx-auto">
            <Link
              href="/anagram"
              className="bg-blue-500 text-white px-4 py-2 rounded"
            >
              AnagramChecker
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
